malariagen_data/ag3.py, malariagen_data/util.py
* Improve memory usage by not computing site filters 
* Support the inline_array argument when setting up dask arrays from zarr - this can improve dask task ordering
=> Improve memory; support inline_array

malariagen_data/ag3.py, malariagen_data/util.py, tests/test_ag3.py
* Fix but in type of chunks - should be tuple
* Change variant_contig, variant_position, sample_id to be coords not data vars
* Create call_genotype_mask later
=> Ag3.snp_calls bug fix and minor tweaks

README.md, poetry.lock, pyproject.toml
This PR does some preparation for the v0.5.0 release:
* Update the dev environment.
* Update release notes in the README.
* Bump version.
=> Prep v0.5.0 release

tests/test_ag3.py
=> Reverse expected/actual in tests

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, malariagen_data/ag3.py, pyproject.toml, tests/test_ag3.py
Ag3 haplotypes are currently in pre-release, add a function to provide access.
=> Add Ag3.haplotypes() implementation and tests

malariagen_data/ag3.py, tests/test_ag3.py
=> Adds cohort access to SNP and CNV frequency methods

malariagen_data/ag3.py, tests/test_ag3.py
=> Upgrade `cohorts_analysis` to 20210927

README.md, pyproject.toml
Updates pyproject.toml and README.md
resolves #80
=> v0.15.0 release

malariagen_data/ag3.py, tests/test_ag3.py
Ref [#1540](https://github.com/malariagen/vector-ops/issues/1540)
=> Add variance vars to CNV HMM

malariagen_data/ag3.py, tests/test_ag3.py
* Resolves #55
* Resolves #70
* Resolves #93
=> Improve species metadata

malariagen_data/ag3.py, tests/test_ag3.py
* Resolves #74 
Also simplifies looking up which release a sample set is in.
=> Check release manifest

malariagen_data/ag3.py, tests/test_ag3.py
=> Decode sample_id to str in Ag3.snp_calls() dataset

malariagen_data/ag3.py, tests/test_ag3.py
=> Add effects to allele frequencies

malariagen_data/ag3.py, tests/test_ag3.py
* Resolves #104
* Resolves #103
* Resolves #111 
* Standardise naming of parameters providing an analysis version identifier
* `species_calls -> species_analysis`
* `site_filters -> site_filters_analysis`
=> Misc minor improvements

malariagen_data/ag3.py, tests/test_ag3.py
resolves #118 
Removes nan freq columns and updates tests.
=> Drop cohorts columns below min cohort size when computing frequencies

malariagen_data/ag3.py, malariagen_data/util.py, tests/test_ag3.py
Adds test and fix for subtle bug found within the optimised dask compress function. Resolves #114.
=> Fix bug with optimised dask compress

malariagen_data/ag3.py, notebooks/plot_frequencies_heatmap.ipynb
=> Expose more imshow parameters in plot_frequencies_heatmap

malariagen_data/ag3.py, malariagen_data/util.py, malariagen_data/veff.py, poetry.lock, pyproject.toml, tests/test_ag3.py
This PR proposes some new functions for computing and visualising variant frequencies over space and time, resolves #143.
There are two new main plotting functions:
* `Ag3.plot_frequencies_time_series()` - creates a time series line plot of variant frequencies, with each panel of the plot showing data for a single cohort, and each line showing variant frequencies.
* `Ag3.plot_frequencies_interactive_map()` - creates an ipyleaflet map with markers showing frequencies and widget controls allowing to select which variant, taxon and time period to show data for.
These new plotting functions can be used with either SNP allele frequencies, amino acid change allele frequencies, or gene CNV frequencies. To make this possible, some new functions have been added which create the necessary input …
=> Ag3 functions for space-time analysis of variant frequencies

malariagen_data/ag3.py
Need more information on locate_region, open functions that return zarr, site_annotations.
aa_allele_frequencies not yet supported in datalab.
Resolves #84.
=> Improve doc strings

malariagen_data/ag3.py, tests/test_ag3.py
* Resolves #138 
* Resolves #142 
* Resolves #146
* Resolves #145
* Some optimisation of snp_allele_frequencies_advanced()
=> Misc aesthetics

README.md, malariagen_data/__init__.py, poetry.lock, pyproject.toml, tests/test_package.py
* Release notes
* Bump version
* Poetry update
* Add `__version__`
=> v2.0.0 release prep

malariagen_data/ag3.py, tests/test_ag3.py
=> Fix CNV frequencies bug

malariagen_data/ag3.py
=> Return copies of cached dataframes

malariagen_data/ag3.py
=> Narrow docstrings

malariagen_data/ag3.py, tests/test_ag3.py
* Resolves #210 
* Resolves #213
=> Add parameters to Ag3.haplotypes() and Ag3.cnv_hmm()

malariagen_data/ag3.py, notebooks/igv.ipynb
=> IGV tweaks

malariagen_data/ag3.py
* Code cleanup to simplify how the `sample_query` parameter is handled when computing SNP allele frequencies.
* Also disable progress bars if debug logging is turned on, as these probably don't mix well.
=> Simplify allele frequencies implementations vis-a-vis handling sampe queries

malariagen_data/ag3.py
Perhaps this might help a little to explain what an instance of the Ag3 class represents.
=> Tweak Ag3 repr - add "client"

malariagen_data/ag3.py
* Resolve #240 
* Make `sample_set` parameter optional
=> Fix Ag3.plot_cnv_hmm_coverage()

malariagen_data/ag3.py, tests/test_ag3.py
=> Fix sample metadata dtype

malariagen_data/ag3.py, tests/anopheles_test_data/test_missing_cohorts/v3-config.json, tests/anopheles_test_data/test_missing_species_calls/v3-config.json
=> config.json supplies defaults for ag3

malariagen_data/ag3.py, pyproject.toml
* Add params to Ag3.plot_aim_heatmap()
* Add longitude and latitude to outputs from Ag3 diversity stats functions
* Add Ag3 plot_diversity_stats() function
=> Misc Ag3 tweaks

README.md, pyproject.toml
=> 6.1.0 update

malariagen_data/ag3.py
* Resolves #269 
* Resolves #276 
* Resolves #277
=> Client location, haplotype progress bar, H12 optional parameters

README.md, pyproject.toml
README.md and pyproject.toml updated for version bump with bug fixes.
=> UPDATE TO 6.1.1

.pre-commit-config.yaml, poetry.lock, pyproject.toml, tests/test_ag3.py
ipinfo v4.4.1 is broken, let's avoid it.
* Resolves #299
=> Avoid broken ipinfo

.github/workflows/main.yml, pyproject.toml
=> Try Python 3.10

malariagen_data/anopheles.py
=> Add cohort_size param to plot_snps()

malariagen_data/__init__.py
=> Ensure xarray has zarr backend

malariagen_data/ag3.py, malariagen_data/anopheles.py
Forgot to add docstrings for the extra metadata methods.
Also cleaned up some TODO/FIXME comments which don't seem to need fixing or resolving any more, at least not in my dev environment.
=> Docstrings for Anopheles extra metadata methods

malariagen_data/anopheles.py, notebooks/plot_samples.ipynb
=> Add years, sample_sets, contributors to plot_samples_interactive_map marker titles

malariagen_data/af1.py
=> Add Af1 site filters track for view_alignments()

malariagen_data/anopheles.py, tests/test_anopheles.py
=> Raise error when _snp_df() transcript is not found

malariagen_data/anopheles.py, notebooks/plot_samples.ipynb
Re: #340 
- Doesn't include the dropdown feature of PR #362
- Also doesn't include the marker `icon` param.
- Adds map `height` param.
- Updates `plot_samples.ipynb` with examples.
=> Support basemap str for plot_samples_interactive_map

.github/workflows/coverage.yml, .github/workflows/linting.yml, .github/workflows/notebooks.yml, .github/workflows/release.yml, .github/workflows/tests.yml, pyproject.toml
* Resolve #378 
* Upgrade poetry in CI
=> Add Python 3.11 support

malariagen_data/ag3.py, malariagen_data/anoph/aim_data.py, malariagen_data/anoph/genome_features.py, malariagen_data/anoph/sample_metadata.py, malariagen_data/anoph/snp_data.py, malariagen_data/anopheles.py, notebooks/plot_samples.ipynb, tests/anoph/test_sample_metadata.py
=> Implement plot_samples_bar()

notebooks/plot_h12_h1x.ipynb, tests/anoph/test_cnv_data.py, tests/anoph/test_genome_features.py, tests/anoph/test_sample_metadata.py, tests/test_af1.py
=> Update Af1 cohort refs in notebooks, tests

tests/anoph/test_hap_data.py
=> Add test for sample sets with no phasing data

malariagen_data/util.py
=> Improve performance applying site filters to SNP calls

malariagen_data/anoph/hap_data.py, malariagen_data/anoph/plotly_params.py, malariagen_data/anoph/sample_metadata.py, malariagen_data/anoph/snp_data.py, malariagen_data/anopheles.py, malariagen_data/util.py, notebooks/plot_njt.ipynb, notebooks/plot_pca.ipynb, tests/anoph/conftest.py, tests/anoph/test_aim_data.py, tests/anoph/test_cnv_data.py, tests/anoph/test_hap_data.py, tests/anoph/test_snp_data.py, tests/test_af1.py, tests/test_ag3.py, tests/test_amin1.py, tests/test_pf7_integration.py, tests/test_pv4_integration.py
* Resolves #474 
* Resolves #475 
* Resolves #476 
* Resolves #477 
* Resolves #478 
* Resolves #479 
* Relax typing on `count_samples()`.
=> Misc bug fixes

malariagen_data/af1.py, malariagen_data/ag3.py, malariagen_data/anoph/pca.py, malariagen_data/anoph/sample_metadata.py, malariagen_data/anopheles.py, notebooks/plot_diversity.ipynb, notebooks/plot_njt.ipynb, notebooks/plot_pca.ipynb, tests/anoph/test_pca.py, tests/anoph/test_sample_metadata.py, tests/test_af1.py, tests/test_ag3.py
* Continue working towards #366 here tackling the PCA computation and plotting functions.
* Refactor other plotting functions to use common symbol and color setup code where possible.
* Add notebook to check plotting of diversity stats.
=> Anopheles refactor PCA functions

malariagen_data/af1.py, malariagen_data/ag3.py, malariagen_data/anoph/igv.py, malariagen_data/anopheles.py, notebooks/igv.ipynb, tests/anoph/conftest.py, tests/anoph/test_igv.py, tests/anoph/test_sample_metadata.py
Continue towards #366 with IGV functions.
=> Refactor Anopheles IGV

malariagen_data/anoph/base_params.py, malariagen_data/anopheles.py, malariagen_data/util.py, notebooks/plot_g123_gwss.ipynb, notebooks/plot_h12_h1x.ipynb
Here we speed up G123 and H12 computations by using a faster approach to hashing.
=> Improve G123 and H12 performance

docs/source/_static/switcher.json, pyproject.toml
* Update pyproject.toml to add some more fields, including a `readme` field so the README.md content gets pulled through to PyPI, should resolve #492 
* Add some versions to the docs switcher
=> Maintenance 2024-01-08

docs/source/Af1.rst, docs/source/Ag3.rst, docs/source/Amin1.rst, docs/source/conf.py, docs/source/index.rst, poetry.lock, pyproject.toml
* Improve home page
* Improve preamble to Ag3, Af1 and Amin1 pages
=> Docs improvements

malariagen_data/af1.py, malariagen_data/ag3.py
=> Update support mailing address

malariagen_data/anoph/snp_frq.py
=> Pandas FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'Y' instead

malariagen_data/anoph/fst.py
=> Pandas FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0

malariagen_data/anoph/cnv_data.py, tests/anoph/test_cnv_data.py
=> Add sample_query argument for cnv_discordant_read_calls function

malariagen_data/anoph/dipclust.py
* Resolves #556 
Currently its reporting the number of aa snps, not the number of SNPs used in clustering.
=> Anopheles diplotype clustering - fix n_snps in title

malariagen_data/anoph/base_params.py, malariagen_data/anoph/pca.py, malariagen_data/anoph/pca_params.py, malariagen_data/anoph/snp_data.py, malariagen_data/anopheles.py, tests/anoph/test_pca.py
=> Add defaults for min_minor_ac, max_missing_an

malariagen_data/anoph/base.py, malariagen_data/anoph/sample_metadata.py, tests/anoph/conftest.py, tests/anoph/fixture/missing_metadata/v3/manifest.tsv, tests/anoph/test_base.py, tests/anoph/test_sample_metadata.py
=> Add terms-of-use info to sample_metadata()

malariagen_data/anoph/cnv_data.py
Re: issues #363, #555
~Alternative to PR #577~
=> Skip sample sets missing CNV HMM

malariagen_data/anoph/snp_data.py
=> Pass through chunks when computing biallelic SNP calls

malariagen_data/anoph/base.py, malariagen_data/util.py, notebooks/local_cluster.ipynb, poetry.lock, pyproject.toml
=> Handle dask distributed progress

malariagen_data/anoph/map_params.py
=> Fix center and zoom map parameters to allow int or float values

malariagen_data/anoph/snp_frq.py
=> Set auto_pan False for marker popup in plot_frequencies_map_markers()

malariagen_data/anoph/fst.py, malariagen_data/anoph/g123.py, malariagen_data/anoph/h12.py, malariagen_data/anoph/h1x.py
=> Add toolbar_options to grumbling gridplots

docs/source/Ag3.rst, docs/source/conf.py
=> Add cross_metadata to sample metadata section of Ag3 docs

malariagen_data/anoph/h12.py, malariagen_data/anoph/h1x.py
=> Update cache names

malariagen_data/anopheles.py, notebooks/plot_frequencies_heatmap.ipynb, tests/test_af1.py, tests/test_ag3.py
This PR speeds up computation of gene CNV data by only retrieving HMM data needed for the region or regions requested.
Resolves #654.
=> Gene CNV optimisation

malariagen_data/anoph/base.py
=> Sort discovered_releases numerically

tests/anoph/test_snp_frq.py
=> Prevent sample exclusions during test_plot_frequencies_time_series_with_taxa

malariagen_data/anoph/distance.py, malariagen_data/anoph/distance_params.py
=> Replicate anjl params to avoid global import causing delays

malariagen_data/anoph/cnv_data.py
=> Palette option in `plot_cnv_hmm_heatmap`

docs/source/Ag3.rst
=> Add `karyotype` to the docs

.github/workflows/label_issues.yml
=> Add GitHub workflow to add the triage label to opened, reopened issues

latest/_static/switcher.json
=> Fix latest deployed switcher.json

docs/source/_static/switcher.json
=> Fix URLs in switcher.json

poetry.lock, pyproject.toml
=> Pin numcodecs < 0.16

README.md, malariagen_data/anoph/dipclust.py
Updating to include citation details.
=> Include package-wide citation notes

malariagen_data/anoph/fst.py
Addresses #768. 
Because it is not supposed to happen, it is hard to test that it works.
=> Handle ZeroDivisionError in plot_pairwise_average_fst

README.md
A couple of minor updates to the README. Includes a link to a [new video](https://youtu.be/zddl3n1DCFM) showing how to get set up with VS Code.
=> Readme updates and new dev setup video

latest/_sources/index.rst.txt, v10.0.0/_sources/index.rst.txt, v10.1.0/_sources/index.rst.txt, v10.2.0/_sources/index.rst.txt, v11.0.0/_sources/index.rst.txt, v11.1.0/_sources/index.rst.txt, v12.0.0/_sources/index.rst.txt, v12.0.1/_sources/index.rst.txt, v13.0.0/_sources/index.rst.txt, v13.0.1/_sources/index.rst.txt, v13.0.2/_sources/index.rst.txt, v13.0.3/_sources/index.rst.txt, v13.0.4/_sources/index.rst.txt, v13.1.0/_sources/index.rst.txt, v13.2.0/_sources/index.rst.txt, v13.2.1/_sources/index.rst.txt, v13.3.0/_sources/index.rst.txt, v13.4.0/_sources/index.rst.txt, v13.5.0/_sources/index.rst.txt, v14.0.0/_sources/index.rst.txt, v15.0.0/_sources/index.rst.txt, v15.0.1/_sources/index.rst.txt, v15.1.0/_sources/index.rst.txt, v15.2.0/_sources/index.rst.txt, v15.2.1/_sources/index.rst.txt, v15.2.2/_sources/index.rst.txt, v8.7.0/_sources/index.rst.txt, v8.8.0/_sources/index.rst.txt, v9.0.0/_sources/index.rst.txt, v9.0.1/_sources/index.rst.txt
Re: issue #800
Note: this updates all previous versions of docs stored on the `gh-pages` branch, rather than on `master`.
=> Update contact address in all doc versions
