malariagen/malariagen-data-python

malariagen_data/ag3.py
tests/test_ag3.py

This PR proposes renaming the `seq_id` argument to `contig` instead, because it's a bit more user friendly (intuitive) and also a bit more consistent with the naming conventions that sgkit are following.

Rename seq_id to contig

---

malariagen_data/ag3.py
poetry.lock
pyproject.toml
tests/test_ag3.py

At some point fsspec and/or gcsfs has changed behaviour regarding whether a trailing slash is removed from the initial URL we pass into the Ag3 class, which breaks everything. This PR fixes that to allow compatibility under both old and new fsspec behaviour.

Fix path for fsspec changes

---

malariagen_data/ag3.py
tests/test_ag3.py

This PR makes some enhancements to the Ag3 method which returns an xarray dataset holding data on SNP calls. 
* Rename `Ag3.snp_dataset()` to `Ag3.snp_calls()` - in future I think we'll be returning xarray datasets from other methods, and we don't want to always have to add "_dataset" to the end of every method name that does so.
* Add additional data variables `call_GQ`, `call_AD`, `call_MQ`, `variant_filter_pass_...` to the dataset.
* `Ag3.snp_calls()` now sets up it's own arrays, rather than depending on `snp_sites()` and `snp_genotypes()` - this simplifies the handling of multiple sample sets, which uses `xarray.concat()`.
Btw I decided **not** to include any sample metadata variables for the time being. May revisit that in future.
Resolves #13.

Ag3 SNP xarray dataset enhancements

---

malariagen_data/ag3.py
malariagen_data/util.py
tests/test_ag3.py

In testing the `ag3.snp_calls()` method with site filters applied, some memory and performance issues have come up (https://github.com/pydata/xarray/issues/5054). This PR has a temporary workaround.

Work around memory and performance issues with xarray indexing

---

malariagen_data/ag3.py
malariagen_data/util.py
tests/test_ag3.py

* Add support for a `chunks` argument which defaults to `auto` allowing dask to choose chunk sizes larger than the native zarr size. This speeds-up data retrieval from colab by a factor of ~2.
* Manually compute chunk sizes after dask.array.compress operations.

Optimisations: auto chunks; faster da.compress

---

malariagen_data/ag3.py
malariagen_data/veff.py
tests/test_ag3.py

- fixes bug in intron code (we weren't getting splice site effects due to `else` instead of `elif`.
- removes the single snp effect method/tests, on reflection this wasn't adding anything helpful.
- Adds intron tests.

Ag3 snp effects updates

---

.flake8
.github/workflows/main.yml
.github/workflows/pre-commit.yml
.gitignore
.pre-commit-config.yaml
README.md
malariagen_data/__init__.py
malariagen_data/ag3.py
malariagen_data/util.py
malariagen_data/veff.py
poetry.lock
pyproject.toml
tests/test_ag3.py

This PR sets up the project to use [pre-commit](https://pre-commit.com/). 
The idea is that hooks are added to automatically run code formatters (black, blackdoc, isort) and linters (flake8) whenever any code is committed, so you don't have to worry about running those things manually. 
Also CI is added to ensure these pre-commit checks have been run.
README now includes some documentation for developers on how to install pre-commit.

Setup pre-commit

---

malariagen_data/ag3.py
malariagen_data/util.py
pyproject.toml
tests/test_ag3.py

This PR adds public methods to the Ag3 class for accessing copy number variation (CNV) data from Ag1000G phase 3, in particular:
* Ag3.cnv_hmm()
* Ag3.cnv_coverage_calls()
* Ag3.cnv_discordant_read_calls()
All methods return xarray datasets.

Ag3 CNV methods

---

malariagen_data/ag3.py
malariagen_data/util.py
malariagen_data/veff.py
tests/test_ag3.py

This PR has several pieces of maintenance, which came up as worth doing while working on the SNP effects example notebook. Includes:
* clean up intron effects and make get_effects() a method (resolves #36)
* rename seqid to contig (resolves #37)
* accelerate snp_effects and snp_allele_frequencies with site mask
* fix unnecessary geneset renaming (resolves #41)
* add description to default cols (resolves #42)
* rename maximum to max_af (resolves #43)

Maintenance on SNP effects and allele frequencies functions

---

.github/workflows/main.yml
malariagen_data/ag3.py
poetry.lock
pyproject.toml
tests/test_ag3.py

This PR adds two methods for computing copy number variation by gene, based on the HMM data:
* Ag3.gene_cnv() - compute modal copy number for each sample by gene, for all genes in a contig
* Ag3.gene_cnv_frequencies() - compute the population frequencies of amplifications and deletions, by gene, for all genes in a contig
Also includes some updates to CI and dev environment.

Add methods for computing copy number variation by gene

---

malariagen_data/ag3.py
poetry.lock
tests/test_ag3.py

* Renames the "populations" parameter to "cohorts", resolves #46.
* Also updates the poetry environment, to take advantage of scikit-allel having wheels now (makes for a faster CI run).

Rename populations to cohorts

---

malariagen_data/ag3.py
tests/test_ag3.py

This PR makes a small change to the `snp_effects` and `snp_allele_frequencies` methods to add the site mask columns into the resulting dataframe. This allows the user to retrieve all SNPs but then see which pass which masks if needed. Useful especially where site filters are too strict and interesting resistance SNPs have been filtered out.
Also some refactoring to move shared code to set up a SNP dataframe to a private utility method.

Add site filter columns to SNP dataframes

---

malariagen_data/ag3.py
tests/test_ag3.py

resolves #50
Adds code to `SNP_allele_frequencies` which raises an error if zero samples in cohort (this code was already present for the CNV method which uses cohorts).
Adds tests for both methods.

Raise error if zero samples selected for allele frequency calculations

---

malariagen_data/ag3.py
tests/test_ag3.py

resolves #51 
Adds a method `Ag3.sample_cohorts(sample_sets, analysis)` to access the Ag3 defined cohorts metadata. Tests have also been written for the method, but currently these point at the staging bucket. Once the metadata is copied to the release bucket, the tests should be updated.

Cohort access

---

malariagen_data/ag3.py
tests/test_ag3.py

resolves #78
Once vector-ops PR has been merged and the 20211101 cohorts meta data transferred to release bucket, the tests on this branch need running to check `cohorts_analysis changes`. Once they have passed, it can be reviewed/merged.

Update  `cohorts_analysis` to latest version

---

malariagen_data/ag3.py
tests/test_ag3.py

This PR makes some changes to how the `sample_sets` parameter is handled. In particular:
* Make sure that multiple releases can be requested via all functions that support a `sample_sets` parameter.
* Change the default behaviour of these functions so that data from all samples sets from all available releases are returned by default.
Note that this second point makes a subtle change to how the API behaves. When interacting with public releases, this will currently be equivalent to requesting `sample_sets="v3"`. When accessing pre-releases, this will access everything from v3 to v3.5. The rationale here is that, generally, this change should mean that users can forget about the `sample_sets` parameter for most use cases, which will hopefully make things a little simpler.
Resolves #85. …

Support multiple releases via the sample_sets parameter

---

malariagen_data/ag3.py

resolves #108 
Uses a dictionary of columns and `pandas.concat([df, dict], axis=1)` rather than `df[name] = newcolumn` to avoid dataframe fragmentation warning.

`snp_allele_frequencies()` Pandas Warning - fragmented dataframe

---

malariagen_data/ag3.py
tests/test_ag3.py

resolves #94 
Adds `cohorts_analysis` parameter to `sample_metadata()`, defaults to latest cohorts analysis. This adds the cohort metadata columns to the `sample_metadata()` output.
PR also adds tests.

Add cohorts to sample_metadata()

---

malariagen_data/ag3.py
tests/test_ag3.py

resolves #116 
Adds "frqs_" string to the start of each frequency column name in dataframes produces via `snp_allele_frequencies()` and `cnv_gene_frequencies()`. Updates tests.

Add "frq_" to columns in frequency generating methods

---

malariagen_data/ag3.py
tests/test_ag3.py

resolves #101 
Adds a method which is similar to `snp_allele_frequencies()` except it collapses multi-variant aa-changes and drops unneeded columns.

`ag3.aa_allele_frequencies()` method

---

malariagen_data/ag3.py
tests/test_ag3.py

Adds a `max_coverage_variance` parameter to the CNV frequencies methods, which defaults to the value we normally use for filtering out samples with too noisy HMM CNV data.
* Resolves #128. 
* Resolves #141.

Add sample coverage variance filtering to CNV frequencies methods

---

malariagen_data/ag3.py
tests/test_ag3.py

Add support for contig parameter being a list of contigs to `Ag3.gene_cnv()` and `Ag3.gene_cnv_frequencies()`.
Resolves #162.

Add support for multiple contigs to Ag3 gene_cnv... functions

---

README.md
malariagen_data/ag3.py
poetry.lock
pyproject.toml

Currently igv-notebook is not available from PyPI, so we cannot list it as a dependency. Make it optional, requiring user installation.

igv-notebook as optional dependency

---

malariagen_data/ag3.py
tests/anopheles_test_data/v3/metadata/species_calls_20200422/test_sample_set/samples.species_aim.csv
tests/anopheles_test_data/v3/metadata/species_calls_aim_20220528/test_sample_set/samples.species_aim.csv
tests/test_ag3.py

* Upgrade the default species analysis to use the new (20220528) AIM species metadata.
* Rename `aim_sites()` to `aim_variants()` for naming consistency with `snp_variants()`.
* Upgrade `aim_variants()` to use new AIMs.
* Add `aim_calls()` accessing the precomputed AIMs (supersedes #244).
* Add `plot_aim_heatmap()`.
Resolves #236.

Add new and improved AIMs

---

.github/workflows/main.yml
poetry.lock
pyproject.toml

This PR enables poetry update to complete in a reasonable time frame. Previously update was running for >10 mins with no sign of completing. I don't know why this trick makes poetry better able to resolve dependencies, but when debugging the update I noticed that a lot of the messages related to pandas, and so tried this.

Fix poetry update with explicit pandas version constraints

---

malariagen_data/util.py

Adds logic to logger, if `debug=False`, logger is set to INFO rather than DEBUG.
resolves #273

Fixes DEBUG bug

---

malariagen_data/ag3.py
notebooks/plot_haplotype_networks.ipynb

Haplotype networks coloured by country were breaking if any country name with a space was present. Here we fix that by sanitising the column used for colouring to strip spaces (and other punctuation just to be sure).

Fix haplotype network grey pie segments for countries with a space in the name

---

.github/workflows/linting.yml
.github/workflows/notebooks.yml
.github/workflows/release.yml
.github/workflows/tests.yml
pyproject.toml

This PR sets up two things:
* Automatic versioning based on git tags, via the [poetry-dynamic-versioning](https://pypi.org/project/poetry-dynamic-versioning/) plugin
* A github action to publish to PyPI when a new github tag is created, using the [poetry-publish](https://github.com/marketplace/actions/publish-python-poetry-package) action
If this works, then this will mean that the only thing we ever need to do to create a new PyPI release is to create a new github release.

Auto versionining and release

---

pyproject.toml

Bokeh 3.0 has a [regression](https://github.com/bokeh/bokeh/issues/12614) which breaks stretch sizing modes. Pin bokeh below 3.0 for the time being.

Pin bokeh below 3.0

---

.flake8
.pre-commit-config.yaml
malariagen_data/af1.py
malariagen_data/ag3.py
malariagen_data/amin1.py
malariagen_data/anopheles.py
malariagen_data/mjn.py
malariagen_data/pf7.py
malariagen_data/plasmodium.py
malariagen_data/pv4.py
malariagen_data/util.py
malariagen_data/veff.py
tests/test_af1.py
tests/test_ag3.py
tests/test_amin1.py
tests/test_anopheles.py
tests/test_pf7_integration.py
tests/test_pv4_integration.py

* Resolves #336 
* Also resolves #266 along the way
* Also upgrades pre-commit hooks because of install problems on CI

Fix bug with multiple regions in PCA and snp_allele_counts

---

malariagen_data/ag3.py
malariagen_data/anopheles.py
tests/test_ag3.py

In this PR I have added support for joined chromosomal arms in Ag3 for the `genome_features()` method, following the approach outlined in PR #346. This contributes towards addressing #332. 
- For the private method `_genome_features_array()`, I chose to follow the `_genome_sequence_array()` naming and keep the suffix '_array' even though technically the returned object is a pandas DataFrame. If preferred, we could change this to `_genome_features_frame()` or `_genome_features_df()`.

ag3.genome_features() - add support for joined arms

---

malariagen_data/ag3.py
malariagen_data/anopheles.py
tests/test_ag3.py

In this PR I have added support for joined arms with the `haplotypes()` function, following approaches in #352, #346, #347. Should be the final step in addressing #332. 
As with `snp_calls()` in PR #352 , I have changed `_haplotypes_dataset()` to `_haplotypes_for_contig()`, and implemented an equivalent method in `ag3`. 
Because some sample sets dont have haplotypes, when converting genome coordinates for the left arm of the xr.Dataset, I had to add some logic to say only do this if the left arm ds is not none.

ag3.haplotypes() - add support for joined arms

---

malariagen_data/anopheles.py
tests/test_ag3.py

This PR fixes a bug where if you specified extra metadata with `add_extra_metadata()` and then tried to use those columns for colors or symbols during `plot_haplotype_clustering()` the extra metadata columns could not be found. 
This is because they needed to be added to a list of hover data columns which is used to subset the metadata.

plot_haplotype_clustering() fix - append extra metadata to hover data if specified

---

malariagen_data/af1.py
malariagen_data/ag3.py
malariagen_data/anopheles.py
notebooks/plot_g123_gwss.ipynb
tests/test_af1.py
tests/test_ag3.py
tests/test_anopheles.py

This PR adds support for the G123 genome-wide selection scan statistic for unphased diplotype data.  I have added a test for each `ag3` and `af1`, and a notebook.
To support G123 calculation, I have made a function `_diplotype_frequencies()` analogous to `_haplotype_frequencies()`. As with the `ihs` functions, I've added support for both a `min` and `max_cohort_size`. 
Main question for @alimanfoo, should I implement a segregating site filter? I think its probably needed, because at the minute we are basically windowing by bases rather than SNPs. 
Resolves #305.

Implement G123 gwss method

---

.github/workflows/notebooks.yml
.github/workflows/tests.yml
.gitignore
README.md
malariagen_data/af1.py
malariagen_data/ag3.py
malariagen_data/anoph/base.py
malariagen_data/anopheles.py
malariagen_data/util.py
tests/anoph/test_base.py
tests/test_anopheles.py

This PR begins the work of breaking up the `AnophelesDataResource` class into a number of smaller classes with related and self-contained functionality, as proposed in #366.
Here a new class `AnophelesBase` is created, which assumes responsibility for loading release configuration and accessing release manifests (sample sets).
Note also that some new tests are added which specifically test this new class. These new tests use locally-created data which mimics the organisation and format of data in Ag3 and Af1 but is local and smaller to allow for faster test runs.
Also resolves #368 along the way.

Anopheles refactor part 1 - AnophelesBase

---

malariagen_data/anoph/base.py
malariagen_data/anopheles.py
tests/anoph/test_base.py
tests/test_ag3.py
tests/test_anopheles.py

Move the _prep_sample_sets_param function to the AnophelesBase class, alongside other functions for handling sample sets and releases.
Along the way, loosen handling of duplicate sample sets.

Move _prep_sample_sets_param

---

malariagen_data/anopheles.py
tests/anoph/conftest.py

Resolves #384
Added the two new cohorts to the exceptions in `read_cohort_metadata()`. 
As this is in `anopheles.py`, will have to keep in mind that we would expect cohort analysis for quarters in af1 too.

Add quarter cohorts in `read_cohort_metadata()` exceptions

---

malariagen_data/ag3.py
malariagen_data/amin1.py
malariagen_data/anopheles.py
malariagen_data/util.py

There is something funny going on within the xarray concat() function which is causing a big slowdown when we try to concatenate datasets, such as the datasets that are being concatenated internally within the snp_calls() or haplotypes() functions. A lot of time is being spent within [this list comprehension in particular](https://github.com/pydata/xarray/blob/51554f2638bc9e4a527492136fe6f54584ffa75d/xarray/core/concat.py#L584) and the logic of it doesn't look right (pathological for large dimensions?).
In the mean time, this PR hacks a cut down version of concatenating datasets along a dimension, which is much much faster (like 1000X).

Faster xarray concatenation

---

malariagen_data/ag3.py
malariagen_data/anoph/genome_features.py
malariagen_data/anoph/gplt_params.py
malariagen_data/anoph/snp_data.py
malariagen_data/anopheles.py
notebooks/plot_cnv.ipynb
notebooks/plot_h12_h1x.ipynb
notebooks/plot_ihs_gwss.ipynb

An issue we are experiencing in the selection atlas project is that multiple GWSS plots can cause problems in the browser, like long page load times and unresponsiveness (xref https://github.com/anopheles-genomic-surveillance/selection-atlas/issues/51).
Here we switch all bokeh genome plots to use "webgl" instead of the default "canvas" for the `output_backend` parameter. Webgl in general renders plots faster and can handle plots with more points than canvas. See the [bokeh docs on webgl acceleration](https://docs.bokeh.org/en/latest/docs/user_guide/output/webgl.html#webgl-acceleration) for more info.
In addition to faster and more responsive plots, this also removes the downsampling of glyphs that otherwise happens with the canvas backend when zooming in or out, which is nice.
Because …

Use webgl for bokeh genome plots

---

poetry.lock
pyproject.toml

Previously I had somehow got the idea that ipyleaflet 0.17.0 didn't work on colab. I therefore pinned the dependency to `>0.17.0`. However, perhaps that was a transient thing, because now 0.17.0 seems to work fine on colab. Also, 0.17.0 is actually better than more recent versions because it doesn't have a bug where maps are blank after conversion to html (https://github.com/jupyter-widgets/ipyleaflet/issues/1090). Hence we should allow malariagen_data to be installed with ipyleaflet 0.17.0.

Relax ipyleaflet pinning

---

.github/workflows/notebooks.yml
.github/workflows/tests.yml
tests/test_ag3.py

* Resolves #417 
To solve the assertion errors, I had to update to the latest cohort version to ensure the cohort names match (i.e. accounting for the single mismatch due to the year change) & update the hard-coded expected_frq_columns on `test_gene_cnv_frequencies__max_coverage_variance()`. 
After this, we also need to update the expected number of positions returned from `test_snp_allele_frequencies__str_cohorts__effects()`, as the number of rows in the AF df is higher than the expected one. This is due to the change in cohorts versions.
Not sure whether there was a reason for using the `20211101` version here (e.g. is this a fixed cohorts release for 3.0?) but it seems like a good chance to update the cohorts version for these tests, given that we have `20230516` as the default in the …

Update cohorts version & expected frq col

---

tests/anoph/test_hap_data.py

* Resolves #432
The previous fix on https://github.com/malariagen/malariagen-data-python/pull/433 was using a sample set not used in the fixtures. 
Here, corrected the sample set used, and deleted the assertion to avoid redundancy as the code is the same as in `check_haplotypes()`.

Fix test for sample sets with no phasing data

---

README.md

Deleted an init char in some of the bash commands (as I keep copying it!).

Delete init character on bash examples - `README.md` 

---

malariagen_data/anopheles.py
malariagen_data/plotly_dendrogram.py
notebooks/plot_haplotype_clustering.ipynb

This PR fixes an omission where the `render_mode` parameter is not fully passed through to plotting code. Follow up to #450.

Pass through render_mode when plotting a dendrogram

---

malariagen_data/ag3.py
malariagen_data/anoph/base.py
malariagen_data/anopheles.py
malariagen_data/plotly_dendrogram.py
notebooks/plot_haplotype_clustering.ipynb

This PR swaps out the implementation of plotly dendrogram which was borrowed from the web with a simpler and more performant implementation.
Also switches to using zarr to save data to the results cache to improve performance.
Also fix missing taxon colors for Ag3.
* Resolves #456
* Resolves #466

Improve performance of dendrogram plotting and saving results to the cache

---

malariagen_data/anoph/base.py
malariagen_data/anoph/base_params.py
malariagen_data/anoph/pca_params.py
malariagen_data/anoph/snp_data.py
malariagen_data/anopheles.py
malariagen_data/util.py
notebooks/plot_pca.ipynb
tests/anoph/test_snp_data.py

* Resolves #448 
Adds a new method `biallelic_snp_calls()` which builds a dataset of SNP calls at sites which are biallelic within the selected samples. Note these do not necessarily have to include the reference allele, i.e., sites are included if there are only two alleles observed, regardles of which alleles.
Adds a new method `biallelic_diplotypes()` which computes alternate allele counts per genotype call, generating a 2-dimensional array suitable for use with PCA, neighbour-joining trees, admixture, etc.
Refactors `pca()` to use `biallelic_diplotypes()` internally.
N.B., because the set of input SNPs to PCA will be slightly different as a result of this change, I have bumped the results cache version number for the pca() function. Also the next release of malariagen_data should be a …

Biallelic SNP calls and diplotypes

---

malariagen_data/anoph/cnv_data.py
malariagen_data/anoph/fst.py
malariagen_data/anoph/g123.py
malariagen_data/anoph/gplt_params.py
malariagen_data/anoph/h12.py
malariagen_data/anoph/h1x.py

Bokeh BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead'

---

tests/test_pf7_integration.py
tests/test_pv4_integration.py

Updated files containing paths to parasite GCS staging buckets,`test_pf7_integration.py` and `test_pv4_integration.py`, to use release buckets.

Updated parasite test buckets from staging to release

---

malariagen_data/anoph/fst.py
malariagen_data/anoph/plotly_params.py
notebooks/plot_pairwise_average_fst.ipynb

* Resolves #567.
* Removes warnings associated with pandas chained assignments.
* Dynamically sizes plot based on number of cohorts.
* Adds a title to the plot.
* Disable colouring by default if an annotation is requested in the upper triangle (as the table then contains a mix of two different types of values and the colouring becomes confusing).
* Code simplification.

Fix and improve plotting pairwise average fst

---

malariagen_data/anoph/pca.py
notebooks/plot_pca.ipynb
tests/anoph/test_pca.py

This PR adds two new parameters to the Anopheles `pca()` function to help with situations where you have PCA outliers that need to be excluded:
* `exclude_samples` - This parameter can be a list of samples that will be excluded completely from the PCA analysis.
* `fit_exclude_samples` - This parameter can be a list of samples that will be excluded during the fitting stage of the PCA analysis, but will be included in the projection stage and therefore in the resulting output dataframe.
The `fit_exclude_samples` parameter is particularly useful where you have samples that are outliers but you still want to see where they fall within real geographical or taxonomic structure.
Note that both of these parameters are only applied after the loading of the input data (biallelic diplotypes) has …

Add parameters to the Anopheles pca function to allow better handling of outliers

---

malariagen_data/util.py

* Raises an error rather than a warning if the colab VM is not in the US
* Resolves #620

Raise error if colab VM not in US

---

malariagen_data/anoph/g123.py

Re: issue #609
Avoids `DeprecationWarning` raised by `anoph/g123.py`: "`in1d` is deprecated. Use `np.isin` instead."

Replace np.in1d with np.isin in g123.py

---

malariagen_data/anoph/distance.py
malariagen_data/anoph/distance_params.py
poetry.lock
pyproject.toml
tests/anoph/test_distance.py

A new version of [anjl](https://alimanfoo.github.io/anjl/) is available which provides an implementation of the dynamic neighbour-joining algorithm. The dynamic algorithm is much faster and more scalable than other algorithms.
This PR adds support for the dynamic algorithm and makes it the default.
* Resolves #646

Add support for dynamic neighbour-joining

---

malariagen_data/anoph/genome_features.py

To resolve #558 . 
Currently the funestus GFF is not properly sorted, and so when doing advanced diplotype clustering, the genes are displayed in the wrong order, making it difficult to infer patterns and spans of CNVs. 
Now we sort the GFF by contig, start in the genome_features() function.

sort gff in `genome_features()`

---

malariagen_data/anoph/fst.py

Addresses #598.
Not sure it works all the time yet but so far, so good.

Remove the transient Warning during pytests

---

malariagen_data/anopheles.py

Resolves #667.
It should pass all tests, mostly because there are no CNV frequencies tests yet.

Better error message for gene_cnv_frequencies() if no cohorts are available for the given sample selection parameters

---

malariagen_data/anoph/cnv_data.py
malariagen_data/anoph/cnv_params.py
malariagen_data/anoph/dipclust.py

Resolves #559.
I followed bokeh's lead (and @sanjaynagi's hint) and replaced `NaN`s  with `-1`. I have been trying to use `zhoverformat` to have the `z` value show as `NaN` instead of `-1` but I couldn't find a way to make it work.
Here is a picture of what it looks like:

Ensure that missing CNVs are shown in a different colour in `plot_diplotype_clustering_advanced`

---

malariagen_data/anoph/distance.py

changes the default to `render_mode="svg"` in `plot_njt()` to fix WebGL issues.
resolves #717

Update plot_njt() in distance.py - render_mode="svg"

---

docs/source/_static/switcher.json

Add in entries to the docs version switcher up to v15.0.1.
To limit the number of items a bit I've just included one entry for each minor or major version.

Update switcher.json up to v15.0.1

---

malariagen_data/pf8_config.json
tests/integration/test_pf8.py

Hello, 
Pf8 data objects are currently stored in both Google Cloud Storage (GCS) and Sanger S3. Based on a recent cost analysis, S3 has been identified as the more cost-effective option. As a result, this PR attempts to update Pf8()'s default URL to point to S3.
Cheers, Eyyub

Updates pf8 default url to s3
